### ISSUE TITLE
correcciones

### ISSUE THREAD

**Issue by gastonprieto** [MarcoPiatti/macowins#1]
* no subir los target a los repositorios, se pueden generar nuevamente.
* (sugerencia) no hace falta usar los rombos de composición y agregación, podes no ponerlo y que solo sean asociaciones (va a simplificar tu diagrama)
* las flechas de implementar la interfaz estan mal, deberían ser un triangulo cerrado blanco
* agregar a las flechas de dirección de asociacion 
* en java se suele hacer una entidad (clase, interfaz, enum) por archivo
* tener un solo constructor, esto nos va a facilitar entender cual es el necesario (esto igual lo profundizamos mas adelante)
*  ` double modificarVenta(double precio);` en realidad no modifica la venta (tener efecto) sino que adecua el precio o le agrega una penalizacion o le aplica interes algo similar. En general el modificar esta muy relacionado a tener efecto, tal vez podria tener otro nombre, lo mismo que el de `modificarPrecio`
* `class VentasRegistradas` podría ser `Local/Negocio`?
* El getTipo de la prenda podría devolver el enum, no es necesario el string
* `testGananciaDelDia` es un test que verifica dos casos distintos, seria conveniente que sean dos tests distintos

> La clase prenda podria haberse implementado como abstracta, y cada subtipo ser una subclase

ojo con esto, si en vez de un enum usas subclases, seria un error, porque la herencia se usa para redefinir o agregar comportamiento

**Comment by MarcoPiatti** [comment]
Gracias por la devolucion!
